### ISSUE TITLE
Clean up Unclassified proto-rules

### ISSUE THREAD

**Issue by NikoAri** [microsoft/OfficeCppGuidelines#5]
For a more-or-less up-to-date to-do list see: To-do: Unclassified proto-rules:
https://microsoft.github.io/OfficeCppGuidelines/CppCoreGuidelines.html#S-unclassified

https://microsoft.github.io/OfficeCppGuidelines/CppCoreGuidelines.html

**Comment by ZachHenkel** [comment]
The problem being referenced comes from the upstream document, it does not originate in our fork.
